# Generated by Django 5.0.6 on 2024-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('greetings', models.CharField(max_length=200)),
            ],
        ),
    ]
