# Generated by Django 5.0.6 on 2024-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intergration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('greetings', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
